[pytest]
markers =
    validate_csv: marks tests that validate CSV content
    unmarked: tests without marks
python_files = test_*.py
addopts = -v --html=report_validate_not_xfail.html


rp_endpoint = https://reportportal.epam.com
rp_api_key = xxx
rp_launch = Tests launch
rp_project = kateryna_milich_personal
